export default function artisans_db ()
{ return [
    {
            id: 'faktor_leather',
            name: 'Faktor Leather',
            url:'https://www.faktor-leather.cz',
            tags: ['Ruční šití', 'Zakázková výroba'],
            img: `faktor_leather.jpg`,
        },
        {
            id: 'panek_leather_goods',
            name: "PÁNEK LEATHER GOODS",
            url: 'https://www.instagram.com/panek.leather.goods/',
            tags: ['Ruční šití', 'Zakázková výroba'],
            img: `panek_leather_goods.jpg`,
        },
        {
            id: 'tomsu&knedla',
            name: 'Tomsu & Knedla Leatherworks',
            url: 'https://www.dkkd.cz',
            tags: ['Ruční šití', 'Zakázková výroba'],
            img: `tomsu&knedla.jpg`,
        },
        {
            id: 'olda_podracky',
            name: 'Olda Podracký',
            url: 'https://www.instagram.com/olda_podracky/',
            tags: ['Ruční šití'],
            img: `olda_podracky.jpg`,
        },
        {
            id: 'petr_duben',
            name: 'Petr Duben - Made In Prague ',
            url: 'https://www.instagram.com/dubenpetr/',
            tags: [],
            img: `petr_duben.jpg`,
        },
        {
            id: 'jan_skola',
            name: 'Jan Skola - Tabor ' ,
            url: 'https://www.instagram.com/janskola.handcraftedleather/',
            tags: ['Ruční šití', 'Zakázková výroba'],
            img: `jan_skola.jpg`,
        },
        {
            id: 'joryleatherworking',
            name: 'joryleatherworking',
            url: 'https://www.instagram.com/joryleatherworking/',
            tags: ['Ruční šití', 'Zakázková výroba'],
            img: `joryleatherworking.jpg`,
        },    {
            id: 'fi-ji',
            name: 'FI-JI',
            url: 'http://www.fi-ji.cz',
            tags: ['Ruční šití', 'Zakázková výroba'],
            img: `fi-ji.jpg`,
        },
        {
            id: 'leatherjan',
            name: 'LeatherJan.cz',
            url: 'https://www.leatherjan.cz',
            tags: ['Ruční šití', 'Zakázková výroba'],
            img: `leatherjan.cz.jpg`,
        },
        {
            id: 'krojzl',
            name: 'Krojzl Zakázková výroba Shoemaker',
            url: 'https://www.krojzl.com',
            tags: ['Ševci', 'Zakázková výroba', 'Ruční šití'],
            img: `krojzl.jpg`,
        },    {
            id: 'aura_original',
            name: 'AURA original',
            url: 'https://www.auraoriginal.cz',
            tags: [],
            img: `aura_original.jpg`,
        },
        {
            id: 'ogar',
            name: 'Ogarbags CZ',
            url: 'https://www.ogarbags.cz',
            tags: ['Zakázková výroba'],
            img: `ogar.jpg`,
        },
        {
            id: 'vena_valnoha',
            name: 'vena valnoha',
            url: 'https://www.venavalnoha.cz',
            tags: ['Ruční šití'],
            img: `vena_valnoha.jpg`,
        },    
        {
            id: 'stepan_jirka',
            name: 'Štěpán Jirka',
            url: 'https://www.stepanjirka.cz',
            tags: ['Ruční šití'],
            img: `stepan_jirka.jpg`,
        },
        {
            id: 'tomas_linger',
            name: 'Tomas Linger',
            url: 'https://www.tomaslinger.cz',
            tags: ['Ruční šití', 'Zakázková výroba'],
            img: `tomas_linger.jpg`,
        },
        {
            id: 'sima_prague',
            name: 'Sima Prague',
            url: 'http://www.sima-prague.com/',
            tags: ['Ruční šití', 'Zakázková výroba'],
            img: `sima_prague.jpg`,
        },    {
            id: 'petr_dudek',
            name: 'Petr Dudek',
            url: 'https://www.zkuze.cz',
            tags: ['Ruční šití', 'Zakázková výroba'],
            img: `petr_dudek.jpg`,
        },
        {
            id: 'pavel_hlavka',
            name: 'Pavel Hlavka',
            url: 'https://www.pavelhlavka.cz',
            tags: ['Ruční šití'],
            img: `pavel_hlavka.jpg`,
        },
        {
            id: 'martin_povr',
            name: 'Martin Povr',
            url: 'https://www.instagram.com/saddlery_martin_povr/',
            tags: ['Zakázková výroba'],
            img: `martin_povr.jpg`,
        },    {
            id: 'brasnarstvi_tatiana',
            name: 'Brašnářství Tatiana',
            url: 'https://www.brasnarstvitatiana.cz',
            tags: [],
            img: `brasnarstvi_tatiana.jpg`,
        },
        {
            id: 'km_saddlary',
            name: 'K.M. Saddlary',
            url: 'https://www.kmsaddlery.cz',
            tags: [],
            img: `km_saddlary.jpg`,
        },
        {
            id: 'vyroba_z_kuze_alexar',
            name: 'Výroba z kůže Alexar',
            url: 'https://vyrobazkuze.alexar.cz',
            tags: ['Historická výroba', 'Zakázková výroba'],
            img: `vyroba_z_kuze_alexar.jpg`,
        },    {
            id: 'atelier_horakuze',
            name: 'Ateliér Horakůže',
            url: 'https://www.horakuze.cz',
            tags: ['Ruční šití', 'Zakázková výroba'],
            img: `atelier_horakuze.jpg`,
        },
        {
            id: 'kozene-vyrobky-martin-vozniak',
            name: 'Kožené výrobky Martin Vozniak',
            url: 'https://www.instagram.com/kozenevyrobkyvozniak/',
            tags: [],
            img: `kozene-vyrobky-martin-vozniak.jpg`,
        },
        {
            id: 'tore',
            name: 'TORE',
            url: 'https://www.toreshop.cz',
            tags: [],
            img: `tore.jpg`,
        },    {
            id: 'roman_tlusty_kozene_vyrobky',
            name: 'Roman Tlustý kožené výrobky',
            url: 'https://tlustypi.company.site',
            tags: [],
            img: `roman_tlusty_kozene_vyrobky.jpg`,
        },
        {
            id: 'calvis_office',
            name: 'Calvis Office',
            url: 'https://www.clavisoffice.cz',
            tags: ['Ruční šití', 'Zakázková výroba', ],
            img: `calvis_office.jpg`,
        },
        {
            id: 'ameliae_kabelky',
            name: 'Amelia E. | česká značka kabelek',
            url: 'https://www.ameliae.eu',
            tags: [],
            img: `ameliae_kabelky.jpg`,
        },    {
            id: 'ben_hrubes',
            name: 'Ben Hrubeš',
            url: 'https://www.benhrubes.cz',
            tags: ['Ruční šití', 'Zakázková výroba', 'Ševci'],
            img: `ben_hrubes.jpg`,
        },
        {
            id: 'lawart',
            name: 'Lawart ❖ obuvnický salon',
            url: 'https://www.lawart.cz',
            tags: ['Ruční šití', 'Zakázková výroba', 'Ševci'],
            img: `lawart.jpg`,
        },
        {
            id: 'kozedelnik_jan_planicka',
            name: 'KOŽEDĚLNÍK JAN PLANIČKA',
            url: 'https://www.kozedelnik.cz/',
            tags: [],
            img: `kozedelnik_jan_planicka.jpg`,
        },    {
            id: 'jerva',
            name: 'Jerva',
            url: 'https://www.jerva.cz',
            tags: ['Ruční šití', 'Zakázková výroba'],
            img: `jerva.jpg`,
        },
        {
            id: 'bag4you',
            name: 'bag4you.cz',
            url: 'https://www.bag4you.cz/',
            tags: ['Ruční šití'],
            img: `bag4you.jpg`,
        },    
        {
            id: 'mrkevleather.cz',
            name: 'mrkevleather.cz',
            url: 'https://mrkevleather.cz',
            tags: ['Ruční šití', 'Zakázková výroba', 'Ševci', 'Historická výroba'],
            img: `mrkevleather.cz.jpg`,
        },
        {
            id: 'michal_svec',
            name: 'Michal Švec',
            url: 'https://www.svecmichal.cz',
            tags: ['Ruční šití', 'Zakázková výroba', 'Ševci'],
            img: `michal_svec.jpg`,
        },    {
            id: 'ondruskovic',
            name: 'Ondruškovic',
            url: 'https://www.ondruskovic.com/',
            tags: ['Ruční šití'],
            img: `ondruskovic.jpg`,
        },
        {
            id: 'facebag',
            name: 'Facebag',
            url: 'https://www.facebag.cz',
            tags: [],
            img: `facebag.jpg`,
        },
            {
            id: 'hemrlik',
            name: 'Hemrlík Design',
            url: 'https://www.hemrlik.design',
            tags: ['Ruční šití', 'Zakázková výroba'],
            img: `hemrlik.jpg`,
        },
        {
            id: 'radu_atelier',
            name: 'RaduAtelier',
            url: 'https://www.radu.cz',
            tags: ['Ruční šití', 'Zakázková výroba'],
            img: `radu_atelier.jpg`,
        },
        {
            id: 'taufer',
            name: 'Taufer',
            url: 'https://www.taufercustomsewing.cz',
            tags: ['Zakázková výroba'],
            img: `taufer.jpg`,
        },
        {
            id: 'montmat',
            name: 'MontMat',
            url: 'https://www.montmat.cz/',
            tags: ['Ruční šití'],
            img: `montmat.jpg`,
        },
        {
            id:'poctivyopasek',
            name:'poctivyopasek',
            url:'https://www.poctivyopasek.cz',
            tags: ['Ruční šití', 'Zakázková výroba'],
            img: `poctivyopasek.jpg`,
        },
        {
            id:'brasnarstvi_valesova',
            name: 'Brašnářství Valešová',
            url:'http://www.brasnarstvi-valesova.cz/index.php/home',
            tags: ['Ruční šití', 'Zakázková výroba'],
            img: `brasnarstvi_valesova.jpg`,
        },
        {
            id:'halflung_leather',
            name:'Halflung - Výrobky z kůže',
            url: 'https://halflung.cz',
            tags: ['Ruční šití', 'Zakázková výroba', 'Historická výroba'],
            img: `halflung_leather.jpg`,
        },
        {
            id:'sedlarstvi_spurny',
            name:'Sedlářství Spurný',
            url:'https://www.spurny.net',
            tags: [],
            img: `sedlarstvi_spurny.jpg`,
        },
        {
            id:'dobra',
            name:'Výrobky z kůže - Dobra',
            url:'https://www.dobraczech.cz',
            tags: ['Historická výroba'],
            img: `dobra.jpg`,
        },
        {
            id:'alistaireshop',
            name:'alistaireshop',
            url:'https://www.alistaire.net/',
            tags: ['Ruční šití', 'Historická výroba'],
            img: `alistaireshop.jpg`,
        },
        {
            id:'sedlarstvi_brasnarstvi_haki',
            name:'Sedlářství a brašnářství Haki',
            url:'http://www.sedlarstvi-brasnarstvi.cz/index.html',
            tags: ['Ruční šití', 'Zakázková výroba'],
            img: `sedlarstvi_brasnarstvi_haki.jpg`,
        },
        {
            id:'beliere',
            name:'Béliere',
            url:'https://www.beliere.cz/',
            tags: [],
            img: `beliere.jpg`,
        },
        {
            id:'bacuta',
            name:'bačuta',
            url:'https://www.bacuta.net',
            tags: [],
            img: `bacuta.jpg`,
        },
        {
            id:'manufaktura_el_calvera',
            name:'El Calvera',
            url:'https://www.elcalvera.com',
            tags: ['Zakázková výroba'],
            img: `manufaktura_el_calvera.jpg`,
        },
        {
            id:'eggo',
            name:'Eggo',
            url:'https://eggobag.com',
            tags: ['Zakázková výroba'],
            img: `eggo.jpg`,
        },
        {
            id:'leathery',
            name:'Leathery',
            url:'https://www.leathery.cz/',
            tags: [],
            img: `leathery.jpg`,
        },
        {
            id:'dobag',
            name:'DOBAG',
            url:'https://www.dobag.cz',
            tags: ['Zakázková výroba', 'Ruční šití'],
            img: `dobag.jpg`,
        },
        {
            id:'onaona',
            name:'ONAONA',
            url:'https://www.onaona.store',
            tags: [],
            img: `onaona.jpg`,
        },
        {
            id:'pbg',
            name:'PBG',
            url:'https://www.pbgstudio.com',
            tags: [],
            img: `pbg.jpg`,
        },
        {
            id:'vasky',
            name:'Vasky',
            url:'https://www.vasky.cz/',
            tags: ['Ševci'],
            img: `vasky.jpg`,
        },
        {
            id:'fernando_echeverria',
            name:'Fernando Echeverria',
            url:'https://www.pbgstudio.com',
            tags: [],
            img: `fernando_echeverria.jpg`,
        },
        {
            id:'zakovsky',
            name:'Zakovsky',
            url:'https://www.zakovsky.eu',
            tags: ['Zakázková výroba', 'Ruční šití'],
            img: `zakovsky.jpg`,
        },
    ]
}       